version: '2'
services:
  db:
    image: mysql/mysql-server:5.7.22
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: documents
      MYSQL_USER: software
      MYSQL_PASSWORD: 1234
    volumes:
      - ./database:/var/lib/mysql
      - ./scripts:/test
  web:
    depends_on:
      - db
    image: local-tomcat-jdbc:latest
    ports:
      - "8080:8080"
    environment:
      PSYANN_DB_HOST: db:3306
      PSYANN_DB_USER: software
      PSYANN_DATABASE: documents
      PSYANN_DB_PASSWORD: 1234
    volumes:
      - ./target/PsychometricAnnotator-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
      - ./target/PsychometricAnnotator-1.0-SNAPSHOT:/usr/local/tomcat/webapps/ROOT
